version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sannabeauty-mongo
    ports:
      - "27100:27017" # Host:Container
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
